import Head from 'next/head';
import { useState } from 'react';
import Link from 'next/link';

export default function Home({ data }) {
	const [tasks, setTasks] = useState(data);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<h1>Main page</h1>
				<Link style={{ margin: '10px' }} href='/tasks'>
					Go to tasks
				</Link>
				<Link style={{ margin: '10px' }} href='/cms'>
					Go to CMS
				</Link>
			</main>
		</>
	);
}
